# -*- coding: utf-8 -*-
"""Introdução Data Science Alura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IjnZggKJ9zolBVzxZvD_jd9uUQeHHg_5
"""

import pandas as pd
notas = pd.read_csv('/content/ratings.csv')
notas.head()

"""# Analisando as notas em geral """

notas.shape

notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

notas['nota'].unique()

notas['nota'].value_counts

print("Média =", notas['nota'].mean())
print("Mediana =", notas['nota'].median())

notas.nota.head()

notas.nota.plot(kind='hist')

#histograma

notas.nota.describe()

import seaborn as sns
sns.boxplot(notas.nota)

#metade das notas dadas são 3 e 4

"""# Olhando os filmes"""

filmes = pd.read_csv("/content/movies.csv")
filmes.columns = ["filmeId", "titulo", "genero"]
filmes.head()

"""# Analisando algumas notas específicas por filme """

#query = perguntar

notas.query("filmeId==1").nota.mean()

#colunas cujo filmeId tem o valor 1

notas.query("filmeId==2").nota.mean()

#agrupar os filmes para obter a média da nota de todos os filmes de uma vez

medias_por_filme = notas.groupby("filmeId").mean()["nota"]
medias_por_filme.head()

#distribuição das notas médias 

medias_por_filme.plot(kind='hist')

import matplotlib.pyplot as plt

plt.figure(figsize=(5,8))
sns.boxplot(y=medias_por_filme)

medias_por_filme.describe()

sns.distplot(medias_por_filme)

plt.hist(medias_por_filme)
plt.title("Histograma das médias dos filmes")

filmes.head()

"""# Comparando os filmes: 
# Toy Story e Jumanji
"""

filmes.head(2)

notas_toy_story = notas.query("filmeId==1")
notas_jumanji = notas.query("filmeId==2")
print(len(notas_toy_story), len(notas_jumanji))

print("Nota média de Toy Story: %.2f" % notas_toy_story.nota.mean())
print("Nota média de Jumanji: %.2f" % notas_jumanji.nota.mean())

print("Nota mediana de Toy Story: %.2f" % notas_toy_story.nota.median())
print("Nota mediana de Jumanji: %.2f" % notas_jumanji.nota.median())

sns.boxplot(x = "filmeId", y = "nota", data = notas.query("filmeId in [1,2]"))

